<a href="https://colab.research.google.com/github/turon41/Python-for-ML/blob/main/Module_11(Numpy_02).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

arr = np.random.randint(1 ,100 , size =(10,5)) # sample - 10 , feature - 5

In [2]:
arr.shape

(10, 5)

In [3]:
b = arr.reshape(5,10)

b.shape
b.ndim
b

array([[83, 78, 86, 15, 63, 95, 37, 28, 63, 80],
       [50, 55, 65, 62, 15, 86, 69, 57, 25, 25],
       [47, 90, 37, 43, 76, 22, 51, 67, 71, 58],
       [60, 23,  3, 42, 31, 43, 36, 22, 20, 50],
       [89, 54,  3, 13, 42, 27, 44, 48, 94, 55]])

In [4]:
flatten = b.flatten()
print(flatten.ndim)
print(flatten)      # row wise flattening
print()

column_wise_flattening = np.ravel(b,order= 'C')  # row wise flattening
print(column_wise_flattening)
print()

column_wise_flattening = np.ravel(b,order= 'F')  # column wise flattening
print(column_wise_flattening)

1
[83 78 86 15 63 95 37 28 63 80 50 55 65 62 15 86 69 57 25 25 47 90 37 43
 76 22 51 67 71 58 60 23  3 42 31 43 36 22 20 50 89 54  3 13 42 27 44 48
 94 55]

[83 78 86 15 63 95 37 28 63 80 50 55 65 62 15 86 69 57 25 25 47 90 37 43
 76 22 51 67 71 58 60 23  3 42 31 43 36 22 20 50 89 54  3 13 42 27 44 48
 94 55]

[83 50 47 60 89 78 55 90 23 54 86 65 37  3  3 15 62 43 42 13 63 15 76 31
 42 95 86 22 43 27 37 69 51 36 44 28 57 67 22 48 63 25 71 20 94 80 25 58
 50 55]


In [5]:
a = np.random.randint(1 ,10 , size =(2,3))
b = np.random.randint(20 ,30 , size =(2,3))
print(a)
print()
print(b)

[[9 4 3]
 [1 4 8]]

[[24 25 21]
 [23 29 20]]


# Concatenate

In [6]:
con_row = np.concatenate((a,b),axis=0) # row wise

print(con_row)

print()

con_col = np.concatenate((a,b), axis = 1) # column wise

print(con_col)

[[ 9  4  3]
 [ 1  4  8]
 [24 25 21]
 [23 29 20]]

[[ 9  4  3 24 25 21]
 [ 1  4  8 23 29 20]]


In [7]:
# error

# row wise concetanate korar shomoi column same thakbe
# col wise concat korar shomoi row ta same thakte hobe

x = np.random.randint(1 ,10 , size =(2,3))
y = np.random.randint(1 ,10 , size =(1,3))

r = np.concatenate((x,y),axis =0 )  # row wise
print(r)
s = np.concatenate((x,y),axis =1 )  # column wise
print(r)

[[6 6 3]
 [1 7 2]
 [4 5 2]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [ ]:
# transpose

mat = np.array([[10,20,30],
                [30,40,50]
               ])


transpose = mat.T

print(transpose)

In [ ]:
# array split

a = np.random.randint(1 ,10 , size =(10,))
print(a)
splitted_array = np.array_split(a,3)

print(splitted_array)

# split -> equal division
splitted_array = np.split(a,3)

# arithmetic operator and mathematical functions

In [ ]:
# faster for vectorization

x = np.array([ 10 , 8 , 30 , 100 ])
y = np.array([ 2 , 3 ,4  ,5 ])

add = np.add(x,y) # evabeu lekha jay : x+y
print(add)

sub = np.subtract(x,y)  # evabeu lekha jay : x-y
print(sub)

mul = np.multiply(x,y)  # evabeu lekha jay : x*y
print(mul)

div = np.divide(x,y)   # evabeu lekha jay : x/y
print(div)

remainder = np.remainder(x,y)  # evabeu lekha jay : x%y
print(remainder)

div_mod = np.divmod(x,y)
print(div_mod)


In [ ]:
# mathematical function

# trigonometry

# sin , cos , tan takes values in radian

sin_val = np.sin(x)
print(sin_val)

cos_val = np.cos(x)
print(cos_val)

deg_con = np.rad2deg(x)
print(deg_con)

# deg2rad

In [ ]:
#log

x = np.array([ 10 , 8 , 16 , 100 ])
base_10_log_val = np.log10(x)
print(base_10_log_val)


two_diye_bhag = np.log2(x)
print(two_diye_bhag)

sqrt= np.sqrt(x)
print(sqrt)

In [ ]:
# different
s = np.sum(x)
print(s)

#prefix sum
cumul =np.cumsum(x)  # cumulative sum
print(cumul)

In [ ]:
#broadcasting

x = np.array([ 10 , 8 , 16 , 100 ])

result = x + 2

#rulings = columns er size and vector er size same hote hobe

matrix = np.array([[10,20,30],
                [30,40,50]
               ])


result = matrix + 2

vector = np.array([1,2,3])

result = matrix +vector
print(result)
print()

vector2 = np.array([1,2,3,4])
result = matrix +vector2
print(result)              # error: bcz vector size and column size is not equal

In [ ]:
# comparison - >,< , >= ,<= , == , !=

x = np.array([ 10 , 8 , 16 , 100 ])
y = np.array([ 2 , 3 ,4  ,5 ])

greater_than = x>y

print(greater_than)

equal = x==y

print(equal)

# all () -> shob true kina
# any() -> jekono ekta true ase kina

print(np.all(greater_than))

print(np.any(equal))

In [ ]:
#inplace
x = np.array([ 10 , 8 , 16 , 100 ])

z = x.copy()

print(z)

z.sort()

print(z)   # main array tar copy thke na ei type sorting e

In [ ]:
# copy sorting
print(x)
sort_arr = np.sort(x)

print(sort_arr)     # main array ta copy kre rakha hy,then sort kra hy...main array ta change hy na

print(x)

In [ ]:
# 2d array sorting
mat = np.array([[10,3,5],[8,4,9]])
print(mat)
print()

# horizon/row wise sorting:  axis = 1

hor_sort = np.sort(mat,axis=1)
print(hor_sort)
print()

# Vertical/column wise sorting:  axis = 0

vert_sort = np.sort(mat,axis=0)
print(vert_sort)

# searching

In [ ]:
print(x)

In [ ]:
# np.where( condition , x , y ) if true x , otherwise replace with y ...it will return an array
# np.where(condition)  it will return index

index = np.where(x==8) # returns index
print(index)

arr = np.where(x>8,x,0) # returns array
print(arr)

In [ ]:
print(mat)

In [ ]:
index = np.where(mat>8) # returns index
print(index)

arr = np.where(mat>8,mat,0) # returns array
print(arr)

In [ ]:
x = np.array([ 10,100 , 8 , 16 , 100 ])

maximum_value_indx = np.argmax(x)
minimum_value_indx = np.argmin(x)
max_val = np.max(x)
min_val = np.min(x)

print(maximum_value_indx)
print(minimum_value_indx)
print(max_val)
print(min_val)

# counting in ndarray

In [ ]:
a = np.random.randint(1 ,100 , size =(100,))
print(a)

In [ ]:
value_great_than_60 = np.count_nonzero(a>60)
print(value_great_than_60)

In [ ]:
unique_value,count  = np.unique(a,return_counts=True)
print(unique_value)
print(count)

# statistical function

In [ ]:
import os
print(os.getcwd())


In [ ]:
from google.colab import files
uploaded = files.upload()


In [ ]:
data = np.genfromtxt('student_marks.csv' ,delimiter=',',skip_header=1)

print(data)

In [9]:
from google.colab import files
uploaded = files.upload()

Saving student_marks_updated.csv to student_marks_updated.csv


In [10]:
# data load

data = np.genfromtxt('student_marks_updated.csv' ,delimiter=',',skip_header=1)

print(data)

[[85. 88. 82.]
 [78. 74. 77.]
 [92. 96. 90.]
 [88. 82. 86.]
 [76. 79. 75.]
 [90. 91. 88.]
 [81. 85. 80.]
 [95. 97. 93.]
 [67. 69. 70.]
 [83. 80. 85.]
 [74. 75. 78.]
 [89. 92. 87.]
 [91. 89. 90.]
 [72. 73. 74.]
 [80. 84. 81.]
 [77. 76. 76.]
 [86. 87. 84.]
 [93. 94. 91.]
 [70. 72. 73.]
 [84. 83. 82.]]


In [11]:
# statistics
math_marks = data[::,:1]

print(math_marks.T)  # to see it row wise uses(.T) math_marks.T

max_math_marks = np.max(math_marks)
print(max_math_marks)

min_math_marks = np.min(math_marks)
print(min_math_marks)

average_math_marks = np.mean(math_marks)
print(average_math_marks)

median_math_marks = np.median(math_marks)
print(median_math_marks)

# standard deviation

std_math_marks = np.std(math_marks)
print(std_math_marks)

[[85. 78. 92. 88. 76. 90. 81. 95. 67. 83. 74. 89. 91. 72. 80. 77. 86. 93.
  70. 84.]]
95.0
67.0
82.55
83.5
7.933946054769971


In [13]:
study_hours = np.array([2, 4, 5, 7, 8])
exam_scores = np.array([65, 75, 78, 88, 92])

data = np.array([study_hours, exam_scores])
print(data)

[[ 2  4  5  7  8]
 [65 75 78 88 92]]


In [14]:
correlation = np.corrcoef(data)

print("Correlation Matrix:\n", correlation)

Correlation Matrix:
 [[1.         0.99859154]
 [0.99859154 1.        ]]


# linear algebra

In [16]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

# a er column and b er row same length hote hobe
dot_product = np.dot(A,B)      # matrix multiplication: np.dot(matrix1,matrix2)
print(dot_product)


# trace
print(np.trace(dot_product))

[[ 58  64]
 [139 154]]
212


In [24]:
sq_mat = np.array([[11,21,31],
          [4,5,6],
          [2,7,11]
         ])

det_of_sq = np.linalg.det(sq_mat)

rank_sq = np.linalg.matrix_rank(sq_mat)

print(det_of_sq)

print(rank_sq)

29.00000000000003
3


In [25]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A,B))

[[19 22]
 [43 50]]
