<a href="https://colab.research.google.com/github/turon41/Python-for-ML/blob/main/Module_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
arr = [1,2,3]

print( arr * 5 )

arr = [ x*5 for x in arr]

print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [56]:
import numpy as np

arr1 = np.array([1,2,3])

arr1 = arr1 * 5

print(arr1)

[ 5 10 15]


# Ndarray

In [57]:
import numpy as np

# 1d array
arr1 = np.array([1,2,3,4,5])


# 2d array
arr2 = np.array([ [1,2,3], # row1
                  [4,5,6] #row2
                ])

#3d array

arr3 = np.array([
    #1st floor
    [ [1,2,3], # row1
      [4,5,6]  ], #row2

    #2nd floor

     [[1,2,3], # row1
      [4,5,6]  ], #row2


    #3rd floor
      [[1,2,3], # row1
      [4,5,6]  ] #row2


])

# Array attributes

In [58]:
# dimension
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)


#shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)


#data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)


#size
print(arr1.size)
print(arr2.size)
print(arr3.size)

1
2
3
(5,)
(2, 3)
(3, 2, 3)
int64
int64
int64
5
6
18


# ndarray datatypes

In [59]:
arr = np.array([1,2,3])

print(arr.dtype)

arr = np.array([1.5,2.4,3.2])
print(arr.dtype)

int64
float64


In [60]:
arr = np.array([1,2,3.2])
# upcasted to float
print(arr.dtype)

#upcasted to string
arr = np.array([1,2,3.2,'hello'])
print(arr.dtype)


arr = np.array([1,True,3.25,'hello',])
print(arr.dtype)

float64
<U32
<U32


# selecting a data type for an array

In [61]:
arr = np.array([1,2,300],dtype=np.int16)
print(arr.dtype)
print(arr)




arr = arr.astype(np.int32)
print(arr.dtype)


#error
arr = np.array([1,2,3.2,'hello'],dtype=np.float64)

int16
[  1   2 300]
int32


ValueError: could not convert string to float: 'hello'

# ndarray creation from existing data

In [ ]:
#list

lst = [10,20,30,40 , 40.5]

arr = np.array(lst, dtype=np.int32)

# print(arr)
# print(type(arr))
# print(arr.dtype)


mixed_lst = [10, True , 'Hello' ]

arr = np.array(mixed_lst)

# print(arr)
# print(type(arr))
# print(arr.dtype)


matrix = [ [1,2,3], # row1
           [4,5,6] #row2
                ]

arr = np.array(matrix)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

In [ ]:
#tuple

tpl = (10,20,30)

arr = np.array(tpl,dtype=np.int32)
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

In [ ]:

#set

st = { 1, 2, 3 }

arr = np.array(list(st))
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

In [ ]:
# dictionary

dc = { 'a' : 10 , 'b' : 20 , 'c' :30 }

keys = dc.keys()
values = dc.values()
items = dc.items()

In [ ]:

# keys to ndarray

arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

In [ ]:
# values to ndarray

arr = np.array(list(values))
print(arr)
arr = arr.astype(np.int16)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

In [ ]:
# items to ndarray

arr = np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

# Creating ndarray from scratch

In [ ]:
# np.zeros

arr = np.zeros((2,3),dtype=np.int8)

# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)

arr = np.zeros_like(arr3) ## arr3 shape same
print(arr)
print(arr.shape)

In [ ]:
#np.ones

arr = np.ones((3,4,3),dtype=np.int8)

# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)


arr = np.ones_like(arr3) ## arr3 shape same
print(arr)
print(arr.shape)

In [ ]:

#np.empty
arr = np.empty((4,3),dtype=np.int8)

# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)

arr = np.empty_like(arr3) ## arr3 shape same
print(arr)
print(arr.shape)

In [62]:
#np.full

arr = np.full((4,3),np.inf)

# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)


arr = np.full_like(arr3,np.inf,dtype=np.float64)

print(arr)
print(arr.shape)
print(arr.dtype)

[[[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]]
(3, 2, 3)
float64


# array creation with random values

In [63]:
# np.random.rand(shape)

arr = np.random.rand(2,3) # 0 ->1

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0.8163728  0.86674    0.05489403]
 [0.41668511 0.29939512 0.11406633]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [64]:
# np.random.randint(start,end, shape)

arr = np.random.randint(1,10 , (2,3))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[3 2 2]
 [1 3 9]]
<class 'numpy.ndarray'>
int64
(2, 3)
2
6


In [65]:
# np.random.uniform(start,end, shape)

arr = np.random.uniform(50,100, (3,3,4))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[73.30092289 70.14564361 93.51644539 81.89206051]
  [80.76248202 53.04753416 91.08470156 85.07669435]
  [94.39862954 58.76939288 92.30500365 86.00432554]]

 [[88.72738739 69.37773051 90.67991446 55.5562476 ]
  [99.32109439 50.17778235 66.02669556 68.0201939 ]
  [90.49978555 57.45554454 92.38306762 59.97298266]]

 [[51.71393916 76.216385   79.59544332 63.62681068]
  [84.28088956 72.88639207 90.20194879 91.29236205]
  [75.65252243 89.53271085 90.95457534 51.25632337]]]
<class 'numpy.ndarray'>
float64
(3, 3, 4)
3
36


# array creation with range functions

In [66]:
# np.arange(first , end , step ) -> similar to range function

arr = np.arange(1 , 10 ,1 )
arr_sh = np.arange(1 , 10 ,1 ).reshape(3,3)
mat = arr.reshape(3,3)

print(arr)
print(mat)
print(f"array with reshape: {arr_sh}")
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
array with reshape: [[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(9,)
1
9


In [67]:
# np.linspace(start , end(included) , koita point pick kra lgbe)

arr = np.linspace(0, 4 ,6)


print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[0.  0.8 1.6 2.4 3.2 4. ]
<class 'numpy.ndarray'>
float64
(6,)
1
6


In [68]:

# np.logspace(start , end(included) , koita point pick kra lgbe, base or base na dewa thkle default base=10)

arr = np.logspace(0 , 4 ,6, base =2)

print(arr)


[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]


# creating matrix for Linear algebra

In [69]:

diagonal_matrix = np.diag([1,2,3,4])

print(diagonal_matrix)
print(diagonal_matrix.shape)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)


In [70]:
# identity matrix

identity_mat = np.eye(4)
# print(identity_mat)
# print(identity_mat.shape)


# np.eye(row , column,k)

mat = np.eye(3,4)
print(mat)
print()

mat = np.eye(3,4,1) # 1 gula ek ghor upore shift hye jbe
print(mat)
print()

mat = np.eye(3,4,-1) # 1 gula ek ghor niche shift hye jbe
print(mat)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


# indexing and slicing

In [71]:
#indexing

print(arr1)
print(arr2)

# arr1[2] = 100

# print(arr1)
arr2[0][2]= 100

print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[  1   2 100]
 [  4   5   6]]


In [72]:
#slicing
#1d = arr[start:end:step]

arr1_mod = arr1[1:4].copy()
arr1[1] = 2


arr1_mod[2] = 200
print(arr1_mod)
print(arr1)

[  2   3 200]
[1 2 3 4 5]


In [73]:

#2d slicing
# arr[ row_start : row_end : step , column_start : column_end : step ]

# print(arr2)

#getting a row

row_0 = arr2[0:1 ,]

row_1= arr2[1: , ]

# print(row_0)
# print(row_1)


#getting a column

col_0 = arr2[:: ,0:1]
col_1 = arr2[::,1:2]

print(col_0)
print(col_1)

#getting a portion


portion = arr2[:: , 1:3]

print(portion)
print()

ar = np.arange(1,10,1).reshape(3,3)
print(ar)
portion = ar[0:3:2,0:3:2]
print(portion)

[[1]
 [4]]
[[2]
 [5]]
[[  2 100]
 [  5   6]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 3]
 [7 9]]


# Advanced Indexing

In [75]:
lst = np.array([ 10 , 20 ,30 ,40 ])

values = lst[[0,3,1]]

print(values)

[10 40 20]


In [91]:
print(arr2)

[[1 2 0]
 [0 0 0]]


In [89]:

print(arr2)
print(arr2[[0,1] , [1,2]])
print()


# boolean kono kichu diye
print(arr2[arr>1])
print()

arr2[arr2>2] = 0
print(arr2)

[[1 2 0]
 [0 0 0]]
[2 0]

[1 2 0 0 0 0]

[[1 2 0]
 [0 0 0]]


In [84]:
print(arr2)

[[1 2 0]
 [0 0 0]]


In [87]:
arr  = np.array([[10,20,30] , [100,200,300] ] )

# iteration
print(arr3)
for i in np.nditer(arr):   # nested loop charai sob value dekhte parchi ei func use kre
    print(i)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
10
20
30
100
200
300
